spring:
  datasource:
    url: jdbc:postgresql://192.168.0.188:5432/ai_coach_chiselbot
    username: chisel_admin
    password: ghkdlxld1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 주의: 운영 DB엔 위험. 개발에서만.
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
    show-sql: true
    open-in-view: false

  application:
    name: chiselbot

  # ★여기로 옮김: spring.mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: oseungun311@gmail.com
    password: "xbef nfaq puie tclp"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

jwt:
  secret: "VGhpc0lzQVNlY3JldEtleUZvckpXVFQxMjM0NTZBUElLRVkzNDQzMjE="
  expiration-in-ms: 3600000

notification:
  policy:
    on-status-done: EMAIL